#!/bin/bash
set -e

docker stop $1

docker create --volumes-from $1 --name rancher-data ghcr.io/kubewarden/ui:latest

docker run --volumes-from rancher-data -v "$PWD:/backup" --rm busybox tar zcvf /backup/rancher-data-backup.tar.gz /var/lib/rancher

docker pull ghcr.io/kubewarden/ui:latest

docker run -d --volumes-from rancher-data --name $1 --restart unless-stopped --privileged -p 80:80 -p 443:443 -e CATTLE_UI_DASHBOARD_INDEX=https://localhost/dashboard/index.html ghcr.io/kubewarden/ui:latest